import { chromium } from '@playwright/test'
const b = await chromium.launch(); const p = await b.newPage()
p.on('console', m => console.log('console:', m.text()))
await p.goto('http://localhost:4173/')
await p.getByRole('button', { name: 'Field notebook' }).click()
await p.getByRole('tab', { name: '30 days', selected: true }).waitFor()
await p.evaluate(() => { document.addEventListener('keydown', e => console.log('keydown', e.key, 'target', e.target.tagName, 'active', document.activeElement?.tagName, document.activeElement?.id, 'prevented', e.defaultPrevented), true) })
await p.keyboard.press('ArrowLeft')
await p.waitForTimeout(300)
console.log('selected:', await p.locator('[role=tab][aria-selected=true]').allTextContents())
await b.close()
